# -*- coding: utf-8 -*-
"""PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P24j4EzRQoYcNfEmggy4Tvn6DjVOfjek
"""

!pip install diffusers transformers accelerate torch safetensors gradio huggingface_hub

from huggingface_hub import login

login()

import torch
import gradio as gr

from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
)

pipe = pipe.to("cuda")

prompt = "A cute white cat wearing sunglasses"

image = pipe(prompt).images[0]

image

def generate(
    prompt,
    negative_prompt,
    guidance_scale
):

    image = pipe(
        prompt,
        negative_prompt=negative_prompt,
        guidance_scale=guidance_scale
    ).images[0]

    return image

demo = gr.Interface(

    fn=generate,

    inputs=[

        gr.Textbox(
            label="Prompt",
            placeholder="A futuristic city at sunset"
        ),

        gr.Textbox(
            label="Negative Prompt",
            placeholder="blurry, low quality"
        ),

        gr.Slider(
            minimum=1,
            maximum=15,
            value=7.5,
            label="Guidance Scale"
        )

    ],

    outputs=gr.Image(
        label="Generated Image"
    ),

    title="AI Image Generator",

    description="Generate images using Stable Diffusion"

)

demo.launch()

demo.launch(share=True)

demo.close()

demo.launch(share=True)

